### ISSUE TITLE
Problem with Avatar Photos

### ISSUE THREAD

**Issue by peskarolo** [joshvermaire/node-tweetbot#2]
First of all congrats for this excellent tutorial. 
HOwever I have a problem with Avatar Photos, when I change the default location of node-tweetbot folder the avatars photos disappear from the screen notification... any idea..?

PD: Can I execute the program in background without having the terminal open?

**Comment by joshvermaire** [comment]
If you stopped it from running (Ctrl + c) and then restarted it in the new location, it should work again.. but in case it doesn't you'll have to manually go in and put the location of the temp folder in the node-tweetbot folder.

If you look at https://github.com/joshvermaire/node-tweetbot/blob/master/app.js#L62, you can change that url to whatever you would like. So that line would read:

```
var filename= "/Users/joshvermaire/github/joshvermaire/node-tweetbot/temp/"+hash+".png";
```

You actually can have it execute in the background, but there are a few steps involved.
1. Open your terminal
2. Type screen
3. Hit space (unless it goes straight to the command line)
4. Go into your node-tweetbot directory
5. Do the normal `node app.js`
6. Hit Ctrl-a then Ctrl-d
7. Then you can close your terminal and it will continue to run.

In the event you ever want to open that session up again.
1. Open your terminal
2. Type `screen -ls` which should give you a list of the sessions still open. You'll see something like: `23109.ttys005.mothership  (Detached)`
3. Type `screen -r 23109.ttys005.mothership` while replacing the screen id with what you see in #2
4. You can then stop the app from running with Ctrl + c and close the session with `exit`

Maybe we could do a few things to make this easier...

Let me know if you have questions.

Josh

**Comment by peskarolo** [comment]
Thanks to answer me so quickly! 

The problem about the avatar still happens, I change the path of filename but the pictures of the avatar disappear (actually is not a big problem for me, I've leave the folder node-tweetbot in the home folder and works well)

About the execution in background, your advice works for me. But now I have another question. I've tried a create a simple shell script for when start the Mac it executes automatically:

#!/bin/bash
#Script para arrancar las notificaciones de Tweetbot para Growl
cd ~/node-tweetbot/
screen node app.js
#echo "^A"
#echo "^D"

But I have problems with Ctrl-a and Ctrl-d because them execute in the bash instead in screen... do you know how I can solve it?

Thank you very much one more time!

Carlos

**Comment by joshvermaire** [comment]
I'm actually not the best bash/terminal developer. But I bet someone on StackOverflow would love to help. If you find out how, post back any good news!
